SELECT SPECIALTYNUMBER, SPECIALTYNAME FROM SPECIALTY;

SELECT DOCTORNUMBER, DOCTORNAME, PHONENUMBER, SPECIALTYNAME, SUPERVISOR FROM DOCTOR LEFT JOIN SPECIALTY ON DOCTOR.SPECIALTYNUMBER = SPECIALTY.SPECIALTYNUMBER;

SELECT DOCTORNUMBER, DOCTORNAME, PHONENUMBER, SPECIALTYNUMBER, SUPERVISOR FROM DOCTOR LEFT JOIN SPECIALTY ON DOCTOR.SPECIALTYNUMBER = SPECIALTY.SPECIALTYNUMBER;

SELECT PATIENTNUMBER, PATIENTNAME, PATIENTPHONE, PATIENTEMAIL PATIENTADDRESS, DOCTORNAME, DATEADDEDTOSYSTEM FROM PATIENT LEFT JOIN DOCTOR ON PATIENT.DOCTORNUMBER = DOCTOR.DOCTORNUMBER;

SELECT PATIENTNUMBER, DOCTORNUMBER, PATIENTNAME, PATIENTPHONE, PATIENTEMAIL PATIENTADDRESS, DATEADDEDTOSYSTEM FROM PATIENT LEFT JOIN DOCTOR ON PATIENT.DOCTORNUMBER = DOCTOR.DOCTORNUMBER;

SELECT APPOINTMENTID, APPOINTMENTDATE, BLOODPRESSURE, PATIENTWEIGHT AS "WEIGHT", TREATMENTNOTES, PATIENTNAME, DOCTORNAME 
FROM APPOINTMENT 
LEFT JOIN PATIENT ON APPOINTMENT.PATIENTNUMBER=PATIENT.PATIENTNUMBER
RIGHT JOIN DOCTOR ON DOCTOR.DOCTORNUMBER=APPOINTMENT.DOCTORNUMBER;

SELECT APPOINTMENTID, PATIENTNUMBER, DOCTORNUMBER, APPOINTMENTDATE, BLOODPRESSURE, PATIENTWEIGHT AS "WEIGHT", TREATMENTNOTES
FROM APPOINTMENT 
LEFT JOIN PATIENT ON APPOINTMENT.PATIENTNUMBER=PATIENT.PATIENTNUMBER
LEFT JOIN DOCTOR ON APPOINTMENT.DOCTORNUMBER=DOCTOR.DOCTORNUMBER;

SELECT MEDICINEID, MEDICINE FROM MEDICINE;

SELECT ALLERGYID, ALLERGY FROM ALLERGY;

SELECT ALLERGYID, PATIENTID FROM PATIENTALLERGY;

SELECT APPOINTMENTID, MEDICINEID FROM PATIENTMEDICINE;