Create table Specialty(
    SpecialtyNumber int generated by default as identity Primary Key,
    SpecialtyName varchar(25) not null
);


create table Doctor(
    DoctorNumber int generated by default as identity Primary Key,
    DoctorName varchar(50) not null,
    PhoneNumber varchar(15) not null,
    SpecialtyNumber int not null,
    --Need to add foreign key of specialty
    CONSTRAINT fk_spec foreign key (SpecialtyNumber)
    REFERENCES Specialty (SpecialtyNumber) on UPDATE CASCADE on delete cascade
);

Create table Patient(
    PatientNumber int generated by default as identity Primary Key,
    PatientName varchar(50) not null,
    PatientPhone varchar(15) not null,
    PatientEmail varchar(50),
    PatientAddress varchar(50) not null,
    DateAddedtoSystem date not null,
    DoctorNumber int not null,
    --need to add foreign key of doctor
    CONSTRAINT fk_doc foreign key (DoctorNumber)
    REFERENCES Doctor (DoctorNumber) on UPDATE CASCADE on delete cascade
);

Create table Appointment(
    AppointmentiD int generated by default as identity Primary Key,
    AppointmentDate datetime not null,
    BloodPressure varchar(20) not null,
    Pulse tinyint not null,
    TreatmentNotes VARCHAR(250)
    DoctorNumber INT NOT NULL,
    PatientNumber int not null,
    --need to add foreign key doctor and patient
    CONSTRAINT fk_patient foreign key (PatientNumber)
    REFERENCES Patient (PatientNumber) on UPDATE CASCADE on delete cascade,
    CONSTRAINT fk_doc01 foreign key (DoctorNumber)
    REFERENCES Doctor (DoctorNumber) on UPDATE CASCADE on delete cascade
);

Create Table Medicine(
    MedicineID int generated by default as identity Primary Key,
    Medicine varchar(50)
);

Create Table Allergy(
    AllergyID int generated by default as identity Primary Key,
    Allergy vharchar(50)
);

Create Table PatientMedicine(
    PatientID int not null,
    MedicineID int not null,
    Primary Key(PatientID, MedicineID),
    CONSTRAINT fk_patient01 foreign key (PatientID)
    REFERENCES Patient (PatientNumber) on UPDATE CASCADE on delete cascade,
    CONSTRAINT fk_med foreign key (MedicineID)
    REFERENCES Medicine (MedicineID) on UPDATE CASCADE on delete cascade
);

Create Table PatientAllergy(
    PatientID int not null,
    AllergyID int not null,
    Primary Key(PatientID, MedicineID),
    CONSTRAINT fk_patient02 foreign key (PatientID)
    REFERENCES Patient (PatientNumber) on UPDATE CASCADE on delete cascade,
    CONSTRAINT fk_alerg foreign key (AllergyIDID)
    REFERENCES Allergy (AllergyID) on UPDATE CASCADE on delete cascade
);